/**
 * Import a Fantasia Archive Electron project (PouchDB dumps) into Postgres.
 *
 * Each `<slug>.txt` in the source directory is a PouchDB replication-stream
 * dump: line 1 is a header, line 2 is `{"docs": [...]}` (some marked
 * `_deleted: true` — tombstones to skip), line 3 is the seq marker. The
 * special files `project-data.txt` (1 doc with project metadata) and
 * `blueprints.txt` (per-type blueprint definitions, possibly user-customized)
 * sit alongside the per-type document dumps.
 *
 * Strategy:
 *  - Find the target user by email (must already exist).
 *  - Create the Project + master ProjectAccess.
 *  - Seed the standard built-in blueprints, then upsert from blueprints.txt
 *    so any user customizations win.
 *  - Insert documents in two passes: first with parentDocId=null (avoiding FK
 *    chicken-and-egg for arbitrary parent ordering), then a second pass sets
 *    parentDocId where the parent actually exists in the import.
 *  - We insert via Prisma directly, not documentService — the dump's paired
 *    relationship fields are already self-consistent, and re-running the
 *    pairing service per doc would be O(N²) writes.
 *  - Image references inside extraFields use `file:///` paths from the
 *    original Electron host; we can't fetch those, so we collect unique paths
 *    into an "images TODO" file the user re-uploads manually via the UI.
 */

import { PrismaClient } from '@prisma/client'
import { readFileSync, readdirSync, writeFileSync } from 'fs'
import { join, basename, dirname, extname, resolve } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))

// Built-in blueprints, generated by extractBlueprints.ts. Lives at
// src/data/blueprints.json in source and dist/data/blueprints.json in the
// prod image; resolve relative to this script regardless of which one runs.
function loadBuiltinBlueprints (): Array<Record<string, unknown>> {
  const candidates = [
    join(__dirname, '..', 'src', 'data', 'blueprints.json'),
    join(__dirname, '..', 'dist', 'data', 'blueprints.json')
  ]
  for (const p of candidates) {
    try { return JSON.parse(readFileSync(p, 'utf8')) as Array<Record<string, unknown>> }
    catch { /* try next */ }
  }
  throw new Error('blueprints.json not found — run npm run build first')
}

async function seedBuiltinBlueprints (prisma: PrismaClient, projectId: string) {
  const builtins = loadBuiltinBlueprints()
  for (let i = 0; i < builtins.length; i++) {
    const bp = builtins[i]
    const slug = (bp._id ?? bp.slug) as string
    await prisma.blueprint.upsert({
      where: { projectId_slug: { projectId, slug } },
      update: {},
      create: {
        projectId,
        slug,
        nameSingular: (bp.nameSingular ?? slug) as string,
        namePlural: (bp.namePlural ?? slug) as string,
        icon: (bp.icon ?? 'mdi-help') as string,
        category: (bp.category ?? '') as string,
        displayOrder: i,
        extraFields: (bp.extraFields ?? []) as object[],
        isBuiltIn: true
      }
    })
  }
}

interface ParsedArgs {
  dir: string
  owner: string
  name?: string
  imagesOut: string
}

function parseArgs (argv: string[]): ParsedArgs {
  const args: Partial<ParsedArgs> = {}
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i]
    if (a === '--dir') args.dir = argv[++i]
    else if (a === '--owner') args.owner = argv[++i]
    else if (a === '--name') args.name = argv[++i]
    else if (a === '--images-out') args.imagesOut = argv[++i]
  }
  if (!args.dir || !args.owner) {
    console.error(`Usage:
  importPouchdb --dir <path> --owner <email> [--name <projectName>] [--images-out <path>]

Imports an Electron-era Fantasia Archive project from a directory of PouchDB
dump .txt files into Postgres. The owner email must match an existing user.`)
    process.exit(2)
  }
  args.dir = resolve(args.dir)
  args.imagesOut = args.imagesOut ?? join(args.dir, 'import-images-todo.txt')
  return args as ParsedArgs
}

interface PouchDoc {
  _id: string
  _rev?: string
  _deleted?: boolean
  type?: string
  extraFields?: Array<{ id: string; value: unknown }>
  // Many other denormalized fields exist on the dump (label, icon, url,
  // hierarchicalPath, hasEdits, editMode, isNew, color, ...) — all derivable
  // from extraFields, so we drop them.
  [key: string]: unknown
}

function readPouchDump (path: string): PouchDoc[] {
  const lines = readFileSync(path, 'utf8').split('\n').filter(l => l.trim())
  if (lines.length < 2) return []
  const body = JSON.parse(lines[1]) as { docs?: PouchDoc[] }
  return (body.docs ?? []).filter(d => !d._deleted)
}

function getField (doc: PouchDoc, id: string): unknown {
  return doc.extraFields?.find(f => f.id === id)?.value
}

function findParentDocId (doc: PouchDoc): string | null {
  const parent = getField(doc, 'parentDoc') as
    | { value?: { _id?: string } }
    | string
    | undefined
  if (!parent || typeof parent === 'string') return null
  return parent.value?._id ?? null
}

function findIsCategory (doc: PouchDoc): boolean {
  return getField(doc, 'categorySwitch') === true
}

// Walks every value in extraFields (including HTML inside wysiwyg fields)
// looking for `file:///` references. Returns unique paths in iteration order.
function collectImagePaths (doc: PouchDoc, out: Set<string>): void {
  if (!doc.extraFields) return
  const fileUriRe = /file:\/\/\/[^"'\s<>)]+/g
  for (const f of doc.extraFields) {
    if (typeof f.value !== 'string') continue
    const matches = f.value.match(fileUriRe)
    if (matches) for (const m of matches) out.add(m)
  }
}

async function main () {
  const args = parseArgs(process.argv.slice(2))
  const prisma = new PrismaClient()

  try {
    const owner = await prisma.user.findFirst({ where: { email: args.owner } })
    if (!owner) {
      console.error(`No user with email "${args.owner}" — register them first via /auth/local/register or OIDC login.`)
      process.exit(1)
    }

    // ── Project metadata ─────────────────────────────────────────────────────
    const projectDataPath = join(args.dir, 'project-data.txt')
    const projectMeta = readPouchDump(projectDataPath)[0] as
      | { projectName?: string; projectCustomCSS?: string }
      | undefined
    if (!projectMeta) {
      console.error(`project-data.txt not found or empty in ${args.dir}`)
      process.exit(1)
    }
    const projectName = args.name ?? projectMeta.projectName ?? 'Imported Project'

    const project = await prisma.project.create({
      data: {
        name: projectName,
        customCss: projectMeta.projectCustomCSS ?? null,
        createdById: owner.id,
        access: { create: { userId: owner.id, role: 'master' } }
      }
    })
    console.log(`✓ Created project "${projectName}" (${project.id})`)

    // ── Blueprints: seed standard set, then overwrite with user's dumps ──────
    await seedBuiltinBlueprints(prisma, project.id)
    const blueprintDocs = readPouchDump(join(args.dir, 'blueprints.txt'))
    for (const bp of blueprintDocs as Array<PouchDoc & {
      namePlural?: string
      nameSingular?: string
      icon?: string
      category?: string
      order?: number
    }>) {
      const slug = bp._id
      await prisma.blueprint.upsert({
        where: { projectId_slug: { projectId: project.id, slug } },
        update: {
          extraFields: (bp.extraFields ?? []) as object[],
          // Preserve user-tweaked metadata too
          namePlural: bp.namePlural ?? slug,
          nameSingular: bp.nameSingular ?? slug,
          icon: bp.icon ?? 'mdi-help',
          category: bp.category ?? '',
          isBuiltIn: false
        },
        create: {
          projectId: project.id,
          slug,
          namePlural: bp.namePlural ?? slug,
          nameSingular: bp.nameSingular ?? slug,
          icon: bp.icon ?? 'mdi-help',
          category: bp.category ?? '',
          displayOrder: bp.order ?? 0,
          extraFields: (bp.extraFields ?? []) as object[],
          isBuiltIn: false
        }
      })
    }
    console.log(`✓ Imported ${blueprintDocs.length} blueprint definitions`)

    // ── Documents: pass 1 (no parent), pass 2 (parent FK) ────────────────────
    const META_FILES = new Set(['project-data.txt', 'blueprints.txt'])
    const dumpFiles = readdirSync(args.dir)
      .filter(f => extname(f) === '.txt' && !META_FILES.has(f) && !f.includes('# Edit conflict'))

    type ToInsert = { id: string; type: string; extraFields: object[]; isCategory: boolean; parentDocId: string | null }
    const all: ToInsert[] = []
    const imagePaths = new Set<string>()

    for (const file of dumpFiles) {
      const slug = basename(file, '.txt')
      const docs = readPouchDump(join(args.dir, file))
      for (const d of docs) {
        all.push({
          id: d._id,
          type: d.type ?? slug,
          extraFields: (d.extraFields ?? []) as object[],
          isCategory: findIsCategory(d),
          parentDocId: findParentDocId(d)
        })
        collectImagePaths(d, imagePaths)
      }
    }
    console.log(`Parsed ${all.length} documents across ${dumpFiles.length} dumps`)

    // Pass 1 — insert with parentDocId=null so we can't violate the self-FK
    // before its target row exists.
    const importedIds = new Set<string>()
    for (const d of all) {
      try {
        await prisma.document.create({
          data: {
            id: d.id,
            projectId: project.id,
            type: d.type,
            extraFields: d.extraFields,
            isCategory: d.isCategory,
            parentDocId: null,
            createdById: owner.id
          }
        })
        importedIds.add(d.id)
      }
      catch (e) {
        console.warn(`  ! Skipped doc ${d.id} (${d.type}):`, (e as Error).message)
      }
    }
    console.log(`✓ Inserted ${importedIds.size}/${all.length} documents (pass 1)`)

    // Pass 2 — set parentDocId where the parent landed in the import.
    let reparented = 0
    let orphaned = 0
    for (const d of all) {
      if (!d.parentDocId || !importedIds.has(d.id)) continue
      if (!importedIds.has(d.parentDocId)) {
        orphaned++
        continue
      }
      await prisma.document.update({
        where: { id: d.id },
        data: { parentDocId: d.parentDocId }
      })
      reparented++
    }
    console.log(`✓ Reparented ${reparented} documents (${orphaned} orphans skipped)`)

    // ── Image TODO ───────────────────────────────────────────────────────────
    if (imagePaths.size > 0) {
      const sorted = Array.from(imagePaths).sort()
      writeFileSync(
        args.imagesOut,
        `# Images referenced by the imported project — re-upload manually via the UI.\n` +
        `# Source paths from the original Electron host:\n` +
        sorted.join('\n') + '\n'
      )
      console.log(`✓ Wrote ${imagePaths.size} image paths to ${args.imagesOut}`)
    }
    else {
      console.log('No image references found.')
    }

    console.log(`\nDone. Open the project at /project/${project.id}`)
  }
  finally {
    await prisma.$disconnect()
  }
}

main().catch(e => {
  console.error(e)
  process.exit(1)
})
