import type { PrismaClient } from '@prisma/client'

// Generated by scripts/extractBlueprints.ts (runs automatically before dev/build)
// eslint-disable-next-line @typescript-eslint/no-var-requires
const blueprints: Array<Record<string, unknown>> = require('../data/blueprints.json')

export async function seedBlueprintsForProject (prisma: PrismaClient, projectId: string) {
  for (let i = 0; i < blueprints.length; i++) {
    const bp = blueprints[i]
    const slug = (bp._id ?? bp.slug) as string

    await prisma.blueprint.upsert({
      where: { projectId_slug: { projectId, slug } },
      update: {},
      create: {
        projectId,
        slug,
        nameSingular: (bp.nameSingular ?? slug) as string,
        namePlural: (bp.namePlural ?? slug) as string,
        icon: (bp.icon ?? 'mdi-help') as string,
        category: (bp.category ?? '') as string,
        displayOrder: i,
        extraFields: (bp.extraFields ?? []) as object[],
        isBuiltIn: true
      }
    })
  }
}
