import type { I_OpenedDocument, I_ShortenedDocument } from "src/interfaces/I_OpenedDocument"
import type { I_ExtraFields, I_Blueprint } from "src/interfaces/I_Blueprint"
import { Loading, QSpinnerGears, extend } from "quasar"
import { documentApi } from "src/services/api/documentApi"
import { useProjectStore } from "src/stores/project"
import { useBlueprintsStore } from "src/stores/blueprints"
import { useAllDocumentsStore } from "src/stores/allDocuments"
import { buildDefaultExtraFields } from "./fieldDefaults"
import { documentPath } from "src/scripts/utilities/projectRoutes"

const SINGLE_AUTOGEN_TYPES = ["singleToNoneRelationship", "singleToSingleRelationship", "singleToManyRelationship"]
const MANY_AUTOGEN_TYPES = ["manyToNoneRelationship", "manyToSingleRelationship", "manyToManyRelationship"]

function getHierarchicalPath (
  document: I_ShortenedDocument | I_OpenedDocument,
  list: I_OpenedDocument[],
  blueprints: I_Blueprint[]
): string {
  const parentField = document.extraFields.find((e) => e.id === "parentDoc")?.value as { value?: { _id?: string } } | undefined
  const parent = parentField?.value
  const parentInList = parent?._id ? list.find((p) => p._id === parent._id) : undefined

  if (!parent || !parentInList) {
    return blueprints.find((b) => b._id === document.type)?.namePlural ?? ""
  }

  const parentName = parentInList.extraFields.find((e) => e.id === "name")?.value as string | undefined
  const upstream = getHierarchicalPath(parentInList, list, blueprints)
  return upstream ? `${upstream} > ${parentName ?? ""}` : (parentName ?? "")
}

function buildShortDocument (
  doc: I_ShortenedDocument,
  dbDocuments: I_OpenedDocument[],
  blueprints: I_Blueprint[]
): I_ShortenedDocument {
  return {
    label: doc.extraFields.find((e) => e.id === "name")?.value,
    icon: doc.icon,
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    id: doc._id as any,
    _id: doc._id,
    url: doc.url,
    type: doc.type,
    extraFields: doc.extraFields,
    hasEdits: false,
    hierarchicalPath: getHierarchicalPath(doc, dbDocuments, blueprints),
    tags: doc.extraFields.find((e) => e.id === "tags")?.value,
    color: doc.extraFields.find((e) => e.id === "documentColor")?.value,
    bgColor: doc.extraFields.find((e) => e.id === "documentBackgroundColor")?.value,
    isCategory: doc.extraFields.find((e) => e.id === "categorySwitch")?.value,
    isMinor: doc.extraFields.find((e) => e.id === "minorSwitch")?.value,
    isDead: doc.extraFields.find((e) => e.id === "deadSwitch")?.value
  }
}

async function createAutoGeneratedDoc (projectId: string, fieldValue: any) {
  if (!fieldValue?.isAutoGenerated) {
    return
  }

  const blueprintsStore = useBlueprintsStore()
  const allDocumentsStore = useAllDocumentsStore()

  const blueprint = blueprintsStore.getBlueprint(fieldValue.type)
  if (!blueprint) {
    return
  }

  const fields = buildDefaultExtraFields(blueprint, { name: fieldValue.label })

  const created = await documentApi.create(projectId, fieldValue.type, { extraFields: fields })

  fieldValue.id = created.id
  fieldValue._id = created.id
  delete fieldValue.isAutoGenerated

  const blueprints = blueprintsStore.getAllBlueprints
  const typeDocs = allDocumentsStore.getDocumentsByType(created.type)?.docs ?? []
  const shortDoc = buildShortDocument(
    {
      _id: created.id,
      id: created.id,
      icon: blueprint.icon,
      url: documentPath(projectId, created.type, created.id),
      type: created.type,
      extraFields: created.extraFields
    } as unknown as I_ShortenedDocument,
    typeDocs as unknown as I_OpenedDocument[],
    blueprints
  )
  allDocumentsStore.addDocument({ doc: shortDoc })
}

/**
 * After a save, re-fetch the authoritative list for each affected type and reconcile
 * the Pinia store to match (add new, update changed, remove deleted).
 */
async function syncTypeFromBackend (projectId: string, type: string) {
  const blueprintsStore = useBlueprintsStore()
  const allDocumentsStore = useAllDocumentsStore()

  const docs = await documentApi.listByType(projectId, type)
  const blueprint = blueprintsStore.getBlueprint(type)
  if (!blueprint) {
    return
  }

  const blueprints = blueprintsStore.getAllBlueprints
  const formatted: I_ShortenedDocument[] = docs.map(d =>
    buildShortDocument(
      {
        _id: d.id,
        id: d.id,
        icon: blueprint.icon,
        url: documentPath(projectId, type, d.id),
        type: d.type,
        extraFields: d.extraFields
      } as unknown as I_ShortenedDocument,
      docs as unknown as I_OpenedDocument[],
      blueprints
    )
  )

  const existing = allDocumentsStore.getDocumentsByType(type)
  if (!existing) {
    allDocumentsStore.mapNewDocumentType({ id: type, timestamp: "", docs: formatted })
    return
  }

  const incomingIds = new Set(formatted.map(d => d._id))
  const existingIds = new Set(existing.docs.map(d => d._id))

  for (const doc of [...existing.docs]) {
    if (!incomingIds.has(doc._id)) {
      allDocumentsStore.removeDocument({ doc })
    }
  }

  for (const doc of formatted) {
    if (existingIds.has(doc._id)) {
      allDocumentsStore.updateDocument({ doc })
    }
    else {
      allDocumentsStore.addDocument({ doc })
    }
  }
}

/**
 * Saves the given document and handles all the needed procedures.
 * Relationship sync is performed server-side; after save all affected types are re-fetched from the API.
 */
export const saveDocument = async (
  document: I_OpenedDocument,
  allOpenedDocuments: I_OpenedDocument[],
  editModeAfterSave: boolean | null,
  disableLoading = false
) => {
  const projectStore = useProjectStore()
  const blueprintsStore = useBlueprintsStore()

  const loadingSetup = {
    message: "<h4>Saving document...</h4>",
    spinnerColor: "primary",
    messageColor: "cultured",
    spinnerSize: 120,
    backgroundColor: "dark",
    // @ts-ignore
    spinner: QSpinnerGears
  }

  const saveTimeout = setTimeout(() => {
    if (!disableLoading) {
      // @ts-ignore
      Loading.show(loadingSetup)
    }
  }, 750)

  const projectId = projectStore.currentProjectId as string
  const currentBlueprint = blueprintsStore.getBlueprint(document.type) as { extraFields: I_ExtraFields[] } | undefined

  const documentCopy = extend<I_OpenedDocument>(true, {}, document)
  allOpenedDocuments = allOpenedDocuments.filter(doc => doc._id !== document._id)

  // Handle auto-generated documents — create them via API first so we get server-assigned IDs
  if (currentBlueprint) {
    for (const field of documentCopy.extraFields) {
      const bpField = currentBlueprint.extraFields.find(e => e.id === field.id)
      if (!bpField) {
        continue
      }

      if (SINGLE_AUTOGEN_TYPES.includes(bpField.type)) {
        await createAutoGeneratedDoc(projectId, (field.value)?.value)
      }

      if (MANY_AUTOGEN_TYPES.includes(bpField.type) && Array.isArray((field.value)?.value)) {
        for (const fv of (field.value).value) {
          await createAutoGeneratedDoc(projectId, fv)
        }
      }
    }
  }

  // Strip UI-only state before persisting
  documentCopy.isNew = false
  documentCopy.hasEdits = false
  documentCopy.editMode = false
  if (documentCopy.scrollDistance !== undefined) {
    delete documentCopy.scrollDistance
  }

  const parentDocId = (documentCopy.extraFields.find(e => e.id === "parentDoc")?.value as string) || undefined
  const isCategory = !!(documentCopy.extraFields.find(e => e.id === "categorySwitch")?.value)
  const payload = {
    extraFields: documentCopy.extraFields,
    isCategory,
    parentDocId: parentDocId || undefined
  }

  let affectedTypes: string[] = [document.type]

  if (document.isNew) {
    const created = await documentApi.create(projectId, document.type, payload)
    documentCopy._id = created.id
  }
  else {
    const result = await documentApi.update(projectId, document.type, document._id, payload)
    affectedTypes = [...new Set([document.type, ...result.affectedTypes])]
  }

  // Re-fetch all affected document types and reconcile the Pinia store
  await Promise.all(affectedTypes.map(type => syncTypeFromBackend(projectId, type)))

  if (editModeAfterSave !== null) {
    documentCopy.editMode = editModeAfterSave
  }

  clearTimeout(saveTimeout)
  if (!disableLoading) {
    Loading.hide()
  }

  return { documentCopy, allOpenedDocuments }
}

/**
 * Relationship field sync is handled server-side; this is a no-op in web mode.
 */
// eslint-disable-next-line @typescript-eslint/no-unused-vars
export const addFieldToDocument = async (_targetDocumentID: string, _fieldID: string, _blueprintID: string) => {
  // no-op: back-reference fields are added by the backend relationship sync
}
