import type { I_OpenedDocument, I_ShortenedDocument } from "src/interfaces/I_OpenedDocument"
import type { I_ExtraFields } from "src/interfaces/I_Blueprint"
import { Loading, QSpinnerGears, extend } from "quasar"
import { documentApi } from "src/services/api/documentApi"

const SINGLE_AUTOGEN_TYPES = ["singleToNoneRelationship", "singleToSingleRelationship", "singleToManyRelationship"]
const MANY_AUTOGEN_TYPES = ["manyToNoneRelationship", "manyToSingleRelationship", "manyToManyRelationship"]

const AUTOGEN_BASE_FIELDS = [
  { id: "name", value: "" },
  { id: "parentDoc", value: "" },
  { id: "documentColor", value: "" },
  { id: "documentBackgroundColor", value: "" },
  { id: "finishedSwitch", value: "" },
  { id: "minorSwitch", value: "" },
  { id: "deadSwitch", value: "" },
  { id: "categorySwitch", value: "" },
  { id: "order", value: "" },
  { id: "tags", value: [] },
  { id: "categoryDescription", value: "" },
  { id: "otherNames", value: [] }
]

async function createAutoGeneratedDoc (projectId: string, fieldValue: any, vueInstance: any) {
  if (!fieldValue?.isAutoGenerated) return

  const blueprint = vueInstance.SGET_blueprint(fieldValue.type)
  const fields = AUTOGEN_BASE_FIELDS.map(f => f.id === "name" ? { id: "name", value: fieldValue.label } : { ...f })

  const created = await documentApi.create(projectId, fieldValue.type, { extraFields: fields })

  fieldValue.id = created.id
  fieldValue._id = created.id
  delete fieldValue.isAutoGenerated

  const shortDoc = vueInstance.mapShortDocument(
    {
      _id: created.id,
      id: created.id,
      icon: blueprint.icon,
      url: `/project/display-content/${created.type}/${created.id}`,
      type: created.type,
      extraFields: created.extraFields
    },
    vueInstance.SGET_allDocumentsByType(created.type).docs
  )
  vueInstance.SSET_addDocument({ doc: shortDoc })
}

async function refreshTypeInVuex (projectId: string, type: string, vueInstance: any) {
  const docs = await documentApi.listByType(projectId, type)
  const blueprint = vueInstance.SGET_blueprint(type)
  const formatted: I_ShortenedDocument[] = docs.map(d =>
    vueInstance.mapShortDocument(
      {
        _id: d.id,
        id: d.id,
        icon: blueprint.icon,
        url: `/project/display-content/${type}/${d.id}`,
        type: d.type,
        extraFields: d.extraFields
      },
      docs as any
    )
  )
  vueInstance.SSET_mapNewDocumentType({ id: type, docs: formatted })
}

/**
 * Saves the given document and handles all the needed procedures.
 * Relationship sync is performed server-side; after save all affected types are re-fetched from the API.
 */
export const saveDocument = async (
  document: I_OpenedDocument,
  allOpenedDocuments: I_OpenedDocument[],
  allDocuments: I_ShortenedDocument[],
  editModeAfterSave: boolean | null,
  vueInstance: any,
  disableLoading = false
) => {
  const loadingSetup = {
    message: "<h4>Saving document...</h4>",
    spinnerColor: "primary",
    messageColor: "cultured",
    spinnerSize: 120,
    backgroundColor: "dark",
    // @ts-ignore
    spinner: QSpinnerGears
  }

  const saveTimeout = setTimeout(() => {
    if (!disableLoading) {
      // @ts-ignore
      Loading.show(loadingSetup)
    }
  }, 750)

  const projectId: string = vueInstance.SGET_currentProjectId
  const currentBlueprint: { extraFields: I_ExtraFields[] } = vueInstance.SGET_blueprint(document.type)

  const documentCopy = extend(true, {}, document) as unknown as I_OpenedDocument
  allOpenedDocuments = allOpenedDocuments.filter(doc => doc._id !== document._id)

  // Handle auto-generated documents — create them via API first so we get server-assigned IDs
  for (const field of documentCopy.extraFields) {
    const bpField = currentBlueprint.extraFields.find(e => e.id === field.id) as I_ExtraFields | undefined
    if (!bpField) continue

    if (SINGLE_AUTOGEN_TYPES.includes(bpField.type)) {
      await createAutoGeneratedDoc(projectId, field.value?.value, vueInstance)
    }

    if (MANY_AUTOGEN_TYPES.includes(bpField.type) && Array.isArray(field.value?.value)) {
      for (const fv of field.value.value) {
        await createAutoGeneratedDoc(projectId, fv, vueInstance)
      }
    }
  }

  // Strip UI-only state before persisting
  documentCopy.isNew = false
  documentCopy.hasEdits = false
  documentCopy.editMode = false
  if (documentCopy.scrollDistance !== undefined) delete documentCopy.scrollDistance

  const parentDocId = (documentCopy.extraFields.find(e => e.id === "parentDoc")?.value as string) || undefined
  const isCategory = !!(documentCopy.extraFields.find(e => e.id === "categorySwitch")?.value)
  const payload = {
    extraFields: documentCopy.extraFields,
    isCategory,
    parentDocId: parentDocId || undefined
  }

  let affectedTypes: string[] = [document.type]

  if (document.isNew) {
    const created = await documentApi.create(projectId, document.type, payload)
    documentCopy._id = created.id
  } else {
    const result = await documentApi.update(projectId, document.type, document._id, payload)
    affectedTypes = [...new Set([document.type, ...result.affectedTypes])]
  }

  // Re-fetch all affected document types and sync Vuex
  await Promise.all(affectedTypes.map(type => refreshTypeInVuex(projectId, type, vueInstance)))

  if (editModeAfterSave !== null) {
    documentCopy.editMode = editModeAfterSave
  }

  clearTimeout(saveTimeout)
  if (!disableLoading) {
    Loading.hide()
  }

  return { documentCopy, allOpenedDocuments }
}

/**
 * Relationship field sync is handled server-side; this is a no-op in web mode.
 */
// eslint-disable-next-line @typescript-eslint/no-unused-vars
export const addFieldToDocument = async (_targetDocumentID: string, _fieldID: string, _blueprintID: string) => {
  // no-op: back-reference fields are added by the backend relationship sync
}
