<template>

  <q-dialog
    v-model="dialogModel"
    @before-hide="triggerDialogClose"
    :persistent="deleteOngoing"
    >
    <q-card
      v-if="!deleteOngoing"
      class="deleteDialog"
      dark
    >
      <q-card-section class="row justify-center text-center">
        <h6 class="text-center q-my-sm">Mass delete documents</h6>
      </q-card-section>

         <q-card-section class="row justify-center q-mx-xl">
          <div>
            The documents will be deleted <span class="text-bold text-secondary">FOREVER</span> with no way to retrieve them.
            <br>
            <span class="text-caption">(unless a previous save of the project exists from earlier time that cointains it)</span>
          </div>
        </q-card-section>

      <q-card-section>
        <div class="row justify-center">

          <q-select
            ref="ref_deleteDocument"
            class="deleteDocumentSelect"
            dark
            popup-content-class="menuResizer"
            menu-anchor="bottom middle"
            menu-self="top middle"
            :options="filteredExistingInput"
            use-input
            multiple
            use-chips
            filled
            label="Selected documents"
            input-debounce="500"
            v-model="deleteDocumentsModel"
            @filter="filterExistingSelect"
          >
            <template v-slot:append v-if="!hideAdvSearchCheatsheetButton">
              <q-btn round dense flat icon="mdi-help-rhombus" @click.stop.prevent="floatingWindowsStore.setAdvSearchWindowVisible"
              >
                <q-tooltip :delay="500">
                  Open search cheatsheet
                </q-tooltip>
              </q-btn>
            </template>
            <template v-slot:option="{ itemProps, itemEvents, opt }">
                <q-item
                  :class="{'hasTextShadow': textShadow, 'isMinor':opt.isMinor}"
                  v-bind="itemProps"
                  v-on="itemEvents"
                  :key="opt.id"
                  :style="`color: ${opt.color}; background-color: ${opt.bgColor}`"
                  @mouseleave="setDocumentPreviewClose"
                >
                <documentPreview
                  :document-id="opt._id"
                  :external-close-trigger="documentPreviewClose"
                  :special-z-index="999999999"
                  :custom-anchor="'top end'"
                  :custom-self="'center left'"
                  :custom-delay="1200"
                />
                  <q-item-section avatar>
                    <q-icon
                      :style="`color: ${retrieveIconColor(opt)}`"
                      :name="(opt.isCategory) ? 'fas fa-folder-open' : opt.icon"
                      />
                  </q-item-section>
                  <q-item-section>
                    <q-item-label>
                      <span class="isDeadIndicator" v-if="opt.isDead">
                        †
                      </span>
                      <span :class="{'isDead': (opt.isDead && !hideDeadCrossThrough)}" v-html="opt.label">
                      </span>
                    </q-item-label>
                    <q-item-label caption class="text-cultured" v-html="opt.hierarchicalPath"></q-item-label>
                    <q-item-label caption class="text-cultured" v-if="opt.tags">
                      <q-chip
                      v-for="(input,index) in opt.tags" :key="index"
                      outline
                      style="opacity: 0.8;"
                      size="12px"
                      class="text-cultured"
                      v-html="`${input}`"
                      >
                      </q-chip>
                    </q-item-label>
                  </q-item-section>
                </q-item>
            </template>
            <template v-slot:selected-item="scope">
              <q-chip
                removable
                dense
                @remove="removeInput(scope)"
                :tabindex="scope.tabindex"
                :color="(scope.opt.isAutoGenerated) ? 'teal-3' : 'accent'"
                text-color="dark"
                class="text-bold"
              >

                <div
                  class="relationShipChipOverlay"
                  @mouseleave="setDocumentPreviewClose"
                />

                <div class="relationShipChipContent">
                  <template v-if="scope.opt.isDead">
                    †
                  </template>
                  {{ stripTags(scope.opt.label) }}
                </div>
                <documentPreview
                  :special-z-index="999999999"
                  :custom-delay="1200"
                  :document-id="scope.opt._id"
                  :external-close-trigger="documentPreviewClose"
                />

              </q-chip>
            </template>
          </q-select>

        </div>

      </q-card-section>

      <q-card-actions align="right" class="q-mb-lg q-mr-sm">
        <q-btn flat label="Cancel" color="accent" v-close-popup class="q-mr-lg" />
          <q-btn
          :outline="deleteDocumentsModel.length !== 0"
          :flat="deleteDocumentsModel.length === 0"
          label="Delete selected documents"
          color="secondary"
          :disable="deleteDocumentsModel.length === 0"
          @click="deleteDocuments"
          />
      </q-card-actions>
    </q-card>

    <q-card v-if="deleteOngoing" dark class="deleteDialog">
        <q-card-section class="row justify-center">
        <h6 class="text-center q-my-sm">Deleting...</h6>
      </q-card-section>

      <q-card-section class="row justify-center q-mx-xl">
        <div>
          Current document: {{currentDocName}}
        </div>
      </q-card-section>

      <q-card-section class="row justify-center q-mx-xl q-mb-lg">
          <q-linear-progress stripe round dark size="20px" :value="progressCounter" color="primary" class="q-mt-sm">
            <div class="absolute-full flex flex-center">
              <q-badge text-color="accent" color="dark" :label="`${deletedDocuments}/${deleteDocumentsModel.length}`" />
            </div>
          </q-linear-progress>
      </q-card-section>
    </q-card>
  </q-dialog>

</template>

<script setup lang="ts">

import { ref, computed, watch, nextTick } from "vue"
import { useQuasar, uid, extend } from "quasar"
import { useAppStores } from "src/composables/useAppStores"
import { useDocumentHelpers } from "src/composables/useDocumentHelpers"
import documentPreview from "src/components/DocumentPreview.vue"
import { documentApi } from "src/services/api/documentApi"
import type { I_ShortenedDocument } from "src/interfaces/I_OpenedDocument"
import type { I_Blueprint } from "src/interfaces/I_Blueprint"
import { advancedDocumentFilter } from "src/scripts/utilities/advancedDocumentFilter"

const props = defineProps<{
  dialogTrigger?: string
  prepickedIds?: string[]
}>()
const emit = defineEmits(["triggerDialogClose", "triggerDialogSubmit"])

const q = useQuasar()
const { dialogsStore, openedDocumentsStore, allDocumentsStore, blueprintsStore, optionsStore, floatingWindowsStore, projectStore } = useAppStores()
const { retrieveIconColor, stripTags } = useDocumentHelpers()

const dialogModel = ref(false)

watch(() => dialogsStore.getDialogsState, (val) => { if (!val) dialogModel.value = false })

watch(() => props.dialogTrigger, (val) => {
  if (val) {
    if (dialogsStore.getDialogsState) {
      return
    }
    dialogsStore.setDialogState(true)
    dialogModel.value = true

    resetLocalData()
    reloadOptions()
    populateDeleteObjectDialog()

    const prepickedIds = props.prepickedIds ?? []
    if (prepickedIds.length > 0) {
      // @ts-ignore
      deleteDocumentsModel.value = allDocumentsStore.getAllDocuments.docs.filter(doc => {
        return prepickedIds.includes(doc._id)
      })
    }
  }
})

function triggerDialogClose () { dialogsStore.setDialogState(false); emit("triggerDialogClose", true) }
function triggerDialogSubmit (val: string) { emit("triggerDialogSubmit", val) }

const ref_deleteDocument = ref<any>(null)

function setDocumentPreviewClose () {
  documentPreviewClose.value = uid()
}

/**
 * Reloads local options
 */
function reloadOptions () {
  textShadow.value = optionsStore.getOptions.textShadow
  hideDeadCrossThrough.value = optionsStore.getOptions.hideDeadCrossThrough
  hideAdvSearchCheatsheetButton.value = optionsStore.getOptions.hideAdvSearchCheatsheetButton
}

/**
 * Hides the advanced search cheatsheet help button in relationship type fields.
 */
const hideAdvSearchCheatsheetButton = ref(false)

/**
 * Determines if the "dead" document type should have a cross-text decoration or not
 */
const hideDeadCrossThrough = ref(false)

/**
 * Determines if text shadow will be shows for accesiblity reasons or not
 */
const textShadow = ref(false)

const documentPreviewClose = ref("")

/**
 * Currently being opened document
 */
const deleteDocumentsModel = ref<I_ShortenedDocument[]>([])

/**
 * Pre-filtered list based on the category inclussion or exlcussion
 */
const existingObjectsFullList = ref<I_ShortenedDocument[]>([])

/**
 * All currently loaded blueprints
 */
const allDocumentBluePrints = ref<I_Blueprint[]>([])

/**
 * Filtered list of items
 */
const filteredExistingInput = ref<I_ShortenedDocument[]>([])

/**
 * Local list copy for filtering in order to not mess up the original list
 */
const listCopy = ref<I_ShortenedDocument[]>([])

function resetLocalData () {
  deleteDocumentsModel.value = []
}

/**
 * Refocuses the first value in the select upon filtering for intuitive keyboard control
 */
async function refocusSelect () {
  await nextTick()
  /*eslint-disable */
  // @ts-ignore
  ref_deleteDocument.value?.setOptionIndex(-1)
  // @ts-ignore
  ref_deleteDocument.value?.moveOptionSelection(1, true)
  /* eslint-enable */
}

/**
 * Filter the pre-filtered list
 */
function filterExistingSelect (val: string, update: (e: () => void) => void) {
  if (val === "") {
    update(() => {
      filteredExistingInput.value = existingObjectsFullList.value.filter((obj) => !obj.isMinor)
      if (filteredExistingInput.value.length > 0) {
        refocusSelect().catch(e => console.log(e))
      }
    })
    return
  }

  update(() => {
    const needle = val.toLowerCase()
    listCopy.value = extend(true, [], existingObjectsFullList.value)
    filteredExistingInput.value = advancedDocumentFilter(needle, listCopy.value, allDocumentBluePrints.value, existingObjectsFullList.value)

    if (filteredExistingInput.value.length > 0) {
      refocusSelect().catch(e => console.log(e))
    }
  })
}

/**
 * Set up all data in to the dialog on popup load
 */
function populateDeleteObjectDialog () {
  allDocumentBluePrints.value = blueprintsStore.getAllBlueprints

  existingObjectsFullList.value = allDocumentsStore.getAllDocuments.docs
}

async function removeInput (scope: {
  index: number
  removeAtIndex: (index: number) => void
}) {
  scope.removeAtIndex(scope.index)

  await nextTick()
  /*eslint-disable */
  // @ts-ignore
  ref_deleteDocument.value?.hidePopup()
  /* eslint-enable */
}

const deleteOngoing = ref(false)
const deletedDocuments = ref(0)
const currentDocName = ref("")
const currentDocument = ref<I_ShortenedDocument | null>(null)

const progressCounter = computed(() => {
  return (deletedDocuments.value / deleteDocumentsModel.value.length)
})

async function deleteDocuments () {
  deleteOngoing.value = true
  deletedDocuments.value = 0
  const projectId = projectStore.currentProjectId as string

  for (const document of deleteDocumentsModel.value) {
    currentDocName.value = document.label

    await documentApi.delete(projectId, document.type, document._id)

    currentDocument.value = allDocumentsStore.getDocument(document._id)
    const dataPass = { doc: currentDocument.value, treeAction: true }

    // @ts-ignore
    openedDocumentsStore.removeDocument(dataPass)
    // @ts-ignore
    allDocumentsStore.removeDocument({ doc: currentDocument.value })

    deletedDocuments.value++
  }

  // Cleanup
  deleteOngoing.value = false
  resetLocalData()
  populateDeleteObjectDialog()
  q.notify({
    group: false,
    type: "positive",
    message: "Mass delete finished"
  })

  triggerDialogClose()
}
</script>

<style lang="scss">
.deleteDialog {
  width: 750px;
  max-width: calc(100vw - 100px) !important;
  margin-top: 100px;
  align-self: flex-start;
  max-height: calc(100vh - 160px) !important;

  h6 {
    display: block;
  }

  .deleteDocumentSelect {
    width: calc(100% - 60px);
    margin-bottom: 30px;
  }
}
</style>
